[project]
name = "agent-trust-boundary"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "deepteam>=1.0.9",
    "langchain-google-genai>=4.3.3",
    "langchain-mcp-adapters>=0.3.2",
    "langgraph>=1.2.11",
    "mcp>=1.29.0",
    "pandas>=3.0.5",
    "python-dotenv>=1.2.2",
]
